version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=jdbc:postgresql://postgres:5432/aimusic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - AI_API_KEY=${AI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - aimusic-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=aimusic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aimusic-network

networks:
  aimusic-network:
    driver: bridge

volumes:
  postgres_data: 