spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
          default-label: main
  security:
    user:
      name: test
      password: test

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key: testkey123 