server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: music-generation-service
          uri: lb://music-generation-service
          predicates:
            - Path=/api/music/**
          filters:
            - StripPrefix=2
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/api/storage/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: quota-service
          uri: lb://quota-service
          predicates:
            - Path=/api/quota/**
          filters:
            - StripPrefix=2
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 1500
        multiplier: 1.5

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: true 