spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: false

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*" 