spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aimusic
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  flyway:
    enabled: true
    baseline-on-migrate: true
    
logging:
  level:
    root: INFO
    com.aimusic: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
  servlet:
    context-path: /api/v1 

suno:
  api:
    base-url: https://api.suno.ai
    api-key: your-api-key-here
    timeout: 30000
    max-retries: 3 