spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
  servlet:
    context-path: /

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.aimusic.backend: DEBUG

# 存储配置
storage:
  location: test-uploads
  max-file-size: 1048576  # 1MB
  allowed-file-types:
    - .mp3
    - .wav
    - .m4a
    - .aac
  url-prefix: /files
  temp-dir: test-temp
  use-original-filename: false
  max-filename-length: 100

# Suno API配置
suno:
  api:
    base-url: http://api.suno.ai
    cookie: test-cookie 